version: "3.1"

services:
  fhir-server:
    image: ghcr.io/bonfhir/medplum-devbox:latest
    ports:
      - "8100:8100"
      - "8103:8103"
    networks:
      - internal-network

  workflow:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    environment:
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}      
    networks:
      - internal-network

volumes:
  n8n_data:

networks:
  internal-network:
    driver: bridge
